// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://exklceslsmplyinxwpuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4a2xjZXNsc21wbHlpbnh3cHV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5MzA1NDUsImV4cCI6MjA4NjUwNjU0NX0.tX6zIVVbO8tv6kxni0qe1vLLb_GauYNWHV9WihRcylM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);